### PR TITLE
Reducing Recursion with foldl, foldr and zip!

### PR DESCRIPTION
**Pull request by Zij-IT**
Hey! I saw your request on Reddit for any improvements that could be made to the code, and since one of the highest upvoted comments had to deal with reducing recursion, I figured I would land a hand on that end.

The comments are individual enough, that each of them are applicable on their own, and they should all pass the tests that you have written.

I would highly recommend looking at the individual commits, instead of the changes as a whole, and see what you like / dislike from there!

If you have any questions regarding any of the changes made, I would be happy to explain what my thought process was when I was making the changes!

**LOOK AT ME:**
I wrote this, so that if you decide you are done with refactoring, and would like to see what someone else would have done, you have that opportunity. If you would rather not merge the changes I have made, that is also cool! It was nice practice for me as well, so thanks :D

### CODE REVIEW

**Comment by siadat** [comment]
Ah this is so nice, thank you so much! @Zij-IT

**Comment by siadat** [comment]
@Zij-IT I read through all of them. They are amazing, thank you so much :)

I was wondering if I could ask 2 questions regarding readability best practices:
 
* Should I always avoid creating temporary values? Or can we count on compiler optimizations to eliminate them?
* Since removing the right most argument makes the code shorter, should I always strive to always do that (eg by reordering the args so eliminating the last arg is possible)?

**Comment by Zij-IT** [comment]
I am no Haskell expert, but here is my two cents:

> Should I always avoid creating temporary values? Or can we count on compiler optimizations to eliminate them?

Temporarily values can be helpful to increase readability. The variables that I removed I felt didn't contribute to the readability of the code.

> Since removing the right most argument makes the code shorter, should I always strive to always do that (eg by reordering the args so eliminating the last arg is possible)?

I don't generally don't write my code in order to enable eta reduction. If the function feels more natural with the arguments, I will generally keep the arguments there. For example:
```haskell
betterGuesserAll :: WordList -> History -> [GuessType]
betterGuesserAll words history =
  map Guess $ filter (\w -> checkAgainstHistory w (DataMap.toList history)) words
```
It would be possible to reorder the parameters and then perform eta-reduction on `words`. However, in doing so, you would also want to reorder the other Guesser functions to keep them consistent. So, in this case, I wouldn't reorder them.

In general, it is good to keep in mind, that shorter does not always mean more readable!

**Comment by siadat** [comment]
@Zij-IT That makes sense. Thank you so much! 🙏

**Pull request merged**
